"""Canvas tool — generates interactive visual HTML/CSS/JS artifacts, charts, and diagrams."""

from __future__ import annotations

import datetime
import html
import logging
import string
import uuid
import webbrowser
from pathlib import Path
from typing import Any

from nova_ai.core.paths import get_config_dir
from nova_ai.core.registry import ToolRegistry
from nova_ai.core.types import ToolResult
from nova_ai.tools._stubs import BaseTool, ToolSpec

logger = logging.getLogger(__name__)

# Upper bound on generated artifact size to prevent runaway HTML generation.
MAX_CANVAS_BYTES = 2 * 1024 * 1024  # 2 MB

CANVAS_HTML_TEMPLATE = string.Template("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://cdn.jsdelivr.net;">
    <title>$title — NOVA AI Canvas</title>
    <!-- Tailwind CSS CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- Chart.js CDN -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- Mermaid.js CDN -->
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({ startOnLoad: true, theme: 'dark' });</script>
    <style>
        :root {
            --bg-color: #0F0B1E;
            --card-bg: #1E1533;
            --accent-purple: #7C3AED;
            --accent-cyan: #06B6D4;
            --text-primary: #F1F5F9;
            --text-muted: #94A3B8;
            --border-color: rgba(124, 58, 237, 0.25);
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            background-color: var(--bg-color);
            color: var(--text-primary);
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            padding: 24px;
            min-height: 100vh;
        }
        .canvas-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding-bottom: 16px;
            margin-bottom: 24px;
            border-bottom: 1px solid var(--border-color);
        }
        .canvas-title {
            font-size: 1.6rem;
            font-weight: 800;
            background: linear-gradient(135deg, var(--accent-purple), var(--accent-cyan));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        .canvas-meta {
            font-size: 0.85rem;
            color: var(--text-muted);
        }
        .canvas-card {
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 14px;
            padding: 24px;
            box-shadow: 0 12px 40px rgba(0, 0, 0, 0.4);
        }
    </style>
</head>
<body>
    <div class="canvas-header">
        <h1 class="canvas-title">$title</h1>
        <div class="canvas-meta">Generated by NOVA AI • $timestamp</div>
    </div>
    <div class="canvas-card">
        $html_body
    </div>
</body>
</html>
""")


def _get_canvas_dir() -> Path:
    canvas_dir = get_config_dir() / "canvas"
    canvas_dir.mkdir(parents=True, exist_ok=True)
    return canvas_dir


@ToolRegistry.register("canvas")
class CanvasTool(BaseTool):
    """Tool to create visual HTML/CSS/JS artifacts rendered for the user."""

    tool_id = "canvas"
    is_local = True

    @property
    def spec(self) -> ToolSpec:
        return ToolSpec(
            name="canvas",
            description=(
                "Create an interactive visual HTML, SVG, Mermaid diagram, or Chart.js canvas/artifact (e.g. data chart, "
                "flowchart, UI mock, dashboard, or visual report). Includes built-in Tailwind CSS, Chart.js, and Mermaid support."
            ),
            parameters={
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "Descriptive title for the visual artifact.",
                    },
                    "html_body": {
                        "type": "string",
                        "description": "HTML/CSS/JS or SVG content to render inside the canvas card. Can use Chart.js, Tailwind classes, or <div class='mermaid'> for diagrams.",
                    },
                    "auto_open": {
                        "type": "boolean",
                        "description": "Whether to automatically open the artifact in the user's default browser.",
                        "default": False,
                    },
                    "sanitize": {
                        "type": "boolean",
                        "description": "Escape the html_body as plain text instead of rendering raw HTML/JS. Use for untrusted content; leave off (default) for Chart.js/Mermaid/Tailwind artifacts.",
                        "default": False,
                    },
                },
                "required": ["title", "html_body"],
            },
            category="visualization",
            timeout_seconds=10.0,
        )

    def execute(
        self,
        title: str,
        html_body: str,
        auto_open: bool = False,
        sanitize: bool = False,
        **kwargs: Any,
    ) -> ToolResult:
        if not title or not html_body:
            return ToolResult(
                tool_name="canvas",
                content="Error: Both title and html_body are required.",
                success=False,
            )

        canvas_dir = _get_canvas_dir()
        artifact_id = str(uuid.uuid4())[:8]
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Sanitize untrusted body content as escaped text; raw HTML is the
        # intended mode for developer-generated Chart.js/Mermaid artifacts.
        rendered_body = html.escape(html_body) if sanitize else html_body

        full_html = CANVAS_HTML_TEMPLATE.safe_substitute(
            title=html.escape(title),
            timestamp=html.escape(timestamp),
            html_body=rendered_body,
        )

        if len(full_html.encode("utf-8")) > MAX_CANVAS_BYTES:
            return ToolResult(
                tool_name="canvas",
                content=(
                    f"Error: generated canvas exceeds the {MAX_CANVAS_BYTES // (1024 * 1024)} MB limit "
                    f"({len(full_html) // 1024} KB). Reduce html_body size."
                ),
                success=False,
            )

        file_path = canvas_dir / f"canvas_{artifact_id}.html"
        try:
            file_path.write_text(full_html, encoding="utf-8")
        except OSError as exc:
            logger.error("Failed to write canvas artifact: %s", exc)
            return ToolResult(
                tool_name="canvas",
                content=f"Error: could not write canvas file '{file_path}': {exc}",
                success=False,
            )
        file_uri = file_path.as_uri()

        if auto_open:
            try:
                webbrowser.open(file_uri)
            except Exception as exc:
                logger.debug("Could not auto-open canvas browser: %s", exc)

        return ToolResult(
            tool_name="canvas",
            content=f"Created Canvas artifact '{title}'. Available at {file_uri}",
            success=True,
            metadata={
                "artifact_id": artifact_id,
                "title": title,
                "file_path": str(file_path),
                "file_uri": file_uri,
                "created_at": timestamp,
                "render": "canvas_panel",
                "html": full_html,
            },
        )
