"""Document & Presentation Generator tool.

Generates Microsoft Word (.docx), PowerPoint (.pptx), and PDF (.pdf) documents
on disk with structured sections, tables, styling, and bullet hierarchy.

Native generation requires the optional ``doc-gen`` extra:

    uv pip install "nova-ai-pro[doc-gen]"

Without it, requests fail loudly with a per-library install hint rather than
silently downgrading to Markdown/TXT fallbacks.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from nova_ai.core.paths import get_config_dir
from nova_ai.core.registry import ToolRegistry
from nova_ai.core.types import ToolResult
from nova_ai.engine.self_optimizer import track_execution
from nova_ai.tools._stubs import BaseTool, ToolSpec

logger = logging.getLogger(__name__)


class DocLibraryMissing(RuntimeError):
    """Raised when the native document library for the requested format is absent."""

    def __init__(self, package: str) -> None:
        self.package = package
        super().__init__(
            f"{package} is required to generate native files with document_generator. "
            'Install it with: uv pip install "nova-ai-pro[doc-gen]" '
            f'(or: uv pip install {package})'
        )


def _create_docx(target_path: Path, title: str, sections: List[Dict[str, Any]]) -> Path:
    """Create a Word .docx document using python-docx if available, or fallback to styled XML/HTML doc."""
    try:
        import docx
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn

        def add_toc_field(document: Any) -> None:
            """Insert a Word TOC field — populated when the user opens the file and updates fields."""
            paragraph = document.add_paragraph()
            run = paragraph.add_run()
            fld_begin = OxmlElement("w:fldChar")
            fld_begin.set(qn("w:fldCharType"), "begin")
            instr = OxmlElement("w:instrText")
            instr.set(qn("xml:space"), "preserve")
            instr.text = 'TOC \\o "1-3" \\h \\z \\u'
            fld_sep = OxmlElement("w:fldChar")
            fld_sep.set(qn("w:fldCharType"), "separate")
            hint = OxmlElement("w:t")
            hint.text = (
                "Right-click and choose 'Update Field' to build the Table of Contents."
            )
            fld_end = OxmlElement("w:fldChar")
            fld_end.set(qn("w:fldCharType"), "end")
            for el in (fld_begin, instr, fld_sep, hint, fld_end):
                run._r.append(el)

        doc = docx.Document()
        doc.add_heading(title, level=0)

        has_headings = any(sec.get("heading") for sec in sections)
        if has_headings and len(sections) >= 2:
            doc.add_heading("Table of Contents", level=1)
            add_toc_field(doc)

        for sec in sections:
            heading = sec.get("heading")
            if heading:
                doc.add_heading(heading, level=1)
            body = sec.get("body", "")
            if body:
                doc.add_paragraph(body)
            bullets = sec.get("bullets", [])
            for b in bullets:
                doc.add_paragraph(b, style="List Bullet")
            table_data = sec.get("table")
            if table_data and isinstance(table_data, list) and len(table_data) > 0:
                first_row = table_data[0]
                if isinstance(first_row, (list, tuple)) and len(first_row) > 0:
                    rows = len(table_data)
                    cols = len(first_row)
                    table = doc.add_table(rows=rows, cols=cols)
                    table.style = "Table Grid"
                    for r_idx, row in enumerate(table_data):
                        for c_idx, cell_value in enumerate(row):
                            if c_idx < cols:
                                table.cell(r_idx, c_idx).text = str(cell_value)

        doc.save(str(target_path))
        return target_path
    except ImportError:
        raise DocLibraryMissing("python-docx") from None


def _create_pptx(target_path: Path, title: str, slides: List[Dict[str, Any]]) -> Path:
    """Create a PowerPoint .pptx presentation using python-pptx if available."""
    try:
        import pptx

        prs = pptx.Presentation()
        # Title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = "Generated by NOVA AI"

        bullet_slide_layout = prs.slide_layouts[1]
        for s in slides:
            slide = prs.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = s.get("title", "Slide")
            tf = slide.placeholders[1].text_frame

            # Add body text first if present
            body = s.get("body", "")
            if body:
                tf.paragraphs[0].text = body

            bullets = s.get("bullets", [])
            for idx, b in enumerate(bullets):
                start_idx = 1 if body else 0
                p = tf.add_paragraph() if (idx + start_idx) > 0 else tf.paragraphs[0]
                p.text = str(b)
                p.level = 0

        prs.save(str(target_path))
        return target_path
    except ImportError:
        raise DocLibraryMissing("python-pptx") from None


def _create_pdf(target_path: Path, title: str, content: str) -> Path:
    """Create a PDF report using reportlab or fpdf if available."""
    try:
        from xml.sax.saxutils import escape as xml_escape

        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

        doc = SimpleDocTemplate(str(target_path), pagesize=letter)
        styles = getSampleStyleSheet()
        story = [
            Paragraph(xml_escape(title), styles["Title"]),
            Spacer(1, 16),
        ]
        for para in content.split("\n\n"):
            if para.strip():
                story.append(Paragraph(xml_escape(para.strip()), styles["Normal"]))
                story.append(Spacer(1, 10))
        doc.build(story)
        return target_path
    except ImportError:
        raise DocLibraryMissing("reportlab") from None


@ToolRegistry.register("document_generator")
class DocumentGeneratorTool(BaseTool):
    """Tool to generate Microsoft Word (.docx), PowerPoint (.pptx), and PDF (.pdf) documents."""

    tool_id = "document_generator"
    is_local = True

    @property
    def spec(self) -> ToolSpec:
        return ToolSpec(
            name="document_generator",
            description=(
                "Generate structured documents and presentations: Word files (.docx), "
                "PowerPoint slide decks (.pptx), or PDF reports (.pdf)."
            ),
            parameters={
                "type": "object",
                "properties": {
                    "doc_type": {
                        "type": "string",
                        "enum": ["docx", "pptx", "pdf"],
                        "description": "Document format to generate.",
                    },
                    "title": {
                        "type": "string",
                        "description": "Document or presentation title.",
                    },
                    "filename": {
                        "type": "string",
                        "description": "Output filename (e.g. 'Project_Proposal.docx', 'Q3_Review.pptx', 'Network_Report.pdf').",
                    },
                    "sections_or_slides": {
                        "type": "array",
                        "items": {"type": "object"},
                        "description": "List of sections (for docx/pdf) or slides (for pptx). Each object can have 'heading'/'title', 'body', 'bullets', and 'table'.",
                    },
                    "output_dir": {
                        "type": "string",
                        "description": "Optional output folder directory path.",
                    },
                },
                "required": ["doc_type", "title", "filename"],
            },
            category="productivity",
            timeout_seconds=20.0,
        )

    @track_execution("document_generator")
    def execute(
        self,
        doc_type: str,
        title: str,
        filename: str,
        sections_or_slides: Optional[List[Dict[str, Any]]] = None,
        output_dir: Optional[str] = None,
        **kwargs: Any,
    ) -> ToolResult:
        if not title or not title.strip():
            return ToolResult(
                tool_name="document_generator",
                content="Error: title is required.",
                success=False,
            )
        if not filename or not filename.strip():
            return ToolResult(
                tool_name="document_generator",
                content="Error: filename is required.",
                success=False,
            )

        doc_type = doc_type.lower().strip()
        items = sections_or_slides or []
        target_dir = (
            Path(output_dir) if output_dir else (get_config_dir() / "documents")
        )
        target_dir.mkdir(parents=True, exist_ok=True)

        target_file = target_dir / filename
        actual_file = target_file

        try:
            if doc_type == "docx":
                actual_file = _create_docx(target_file, title, items)
            elif doc_type == "pptx":
                actual_file = _create_pptx(target_file, title, items)
            elif doc_type == "pdf":
                body_text = (
                    "\n\n".join(
                        f"{item.get('heading', '')}\n{item.get('body', '')}\n"
                        + "\n".join(f"* {b}" for b in item.get("bullets", []))
                        for item in items
                    )
                    or title
                )
                actual_file = _create_pdf(target_file, title, body_text)
            else:
                return ToolResult(
                    tool_name="document_generator",
                    content=f"Unsupported document type: {doc_type}. Must be docx, pptx, or pdf.",
                    success=False,
                )
        except DocLibraryMissing as e:
            return ToolResult(
                tool_name="document_generator",
                content=f"Error: {e}",
                success=False,
                metadata={"missing_package": e.package},
            )
        except Exception as e:
            return ToolResult(
                tool_name="document_generator",
                content=f"File creation failed: {e}",
                success=False,
            )

        return ToolResult(
            tool_name="document_generator",
            content=f"Created '{actual_file.name}' at {actual_file}",
            success=True,
            metadata={
                "doc_type": doc_type,
                "title": title,
                "file_path": str(actual_file),
            },
        )


__all__ = ["DocumentGeneratorTool"]
