"""Default TOML generation (for ``nova init``).

Split out of the original monolithic ``core/config.py``. Re-exported by the
``nova_ai.core.config`` facade.
"""

from __future__ import annotations

from nova_ai.core.config.hardware import HardwareInfo, recommend_engine
from nova_ai.core.config.models import recommend_model

# ---------------------------------------------------------------------------
# Default TOML generation (for ``nova init``)
# ---------------------------------------------------------------------------


def generate_minimal_toml(
    hw: HardwareInfo, engine: str | None = None, *, host: str | None = None
) -> str:
    """Render a minimal TOML config with only essential settings."""
    engine = engine or recommend_engine(hw)
    model = recommend_model(hw, engine)
    gpu_comment = ""
    if hw.gpu:
        mem_label = "unified memory" if hw.gpu.vendor == "apple" else "VRAM"
        gpu_comment = f"\n# GPU: {hw.gpu.name} ({hw.gpu.vram_gb} GB {mem_label})"
    if host:
        engine_host_section = f'\n[engine.{engine}]\nhost = "{host}"\n'
    else:
        engine_host_section = (
            f"\n[engine.{engine}]\n"
            f'# host = "http://localhost:11434"  '
            f"# set to remote URL if engine runs elsewhere\n"
        )
    return f"""\
# NOVA AI configuration
# Hardware: {hw.cpu_brand} ({hw.cpu_count} cores, {hw.ram_gb} GB RAM){gpu_comment}
# Full reference config: nova init --full

[engine]
default = "{engine}"
{engine_host_section}
[intelligence]
default_model = "{model}"

[agent]
default_agent = "simple"

[tools]
enabled = ["code_interpreter", "web_search", "file_read", "shell_exec"]
"""


def generate_default_toml(
    hw: HardwareInfo, engine: str | None = None, *, host: str | None = None
) -> str:
    """Render a commented TOML string suitable for ``~/.nova_ai/config.toml``."""
    engine = engine or recommend_engine(hw)
    model = recommend_model(hw, engine)
    gpu_line = ""
    if hw.gpu:
        gpu_line = f"# Detected GPU: {hw.gpu.name} ({hw.gpu.vram_gb} GB VRAM)"

    model_comment = ""
    if model:
        model_comment = "  # recommended for your hardware"

    result = f"""\
# NOVA AI configuration
# Generated by `nova init`
#
# Hardware: {hw.cpu_brand} ({hw.cpu_count} cores, {hw.ram_gb} GB RAM)
{gpu_line}

[engine]
default = "{engine}"

[engine.ollama]
host = "http://localhost:11434"

[engine.vllm]
host = "http://localhost:8000"

[engine.sglang]
host = "http://localhost:30000"

# [engine.llamacpp]
# host = "http://localhost:8080"
# binary_path = ""

[engine.mlx]
host = "http://localhost:8080"

# [engine.lmstudio]
# host = "http://localhost:1234"

# [engine.exo]
# host = "http://localhost:52415"

# [engine.nexa]
# host = "http://localhost:18181"
# device = ""  # cpu, gpu, npu

# [engine.uzu]
# host = "http://localhost:8080"

# [engine.apple_fm]
# host = "http://localhost:8079"

[intelligence]
default_model = "{model}"{model_comment}
fallback_model = ""
# model_path = ""              # Local weights (HF repo, GGUF file, etc.)
# checkpoint_path = ""         # Checkpoint/adapter path
# quantization = "none"        # none, fp8, int8, int4, gguf_q4, gguf_q8
# preferred_engine = ""        # Override engine for this model (e.g., "vllm")
# provider = ""                # local, openai, anthropic, google
temperature = 0.7
max_tokens = 1024
# top_p = 0.9
# top_k = 40
# repetition_penalty = 1.0
# stop_sequences = ""

[agent]
default_agent = "simple"
max_turns = 10
# tools = ""                   # Comma-separated tool names
# objective = ""               # Concise purpose string
# system_prompt = ""           # Inline system prompt
# system_prompt_path = ""      # Path to system prompt file
context_from_memory = true

[tools.storage]
default_backend = "sqlite"

[tools.mcp]
enabled = true

# [tools.browser]
# headless = true
# timeout_ms = 30000
# viewport_width = 1280
# viewport_height = 720

[server]
host = "0.0.0.0"
port = 8000
agent = "orchestrator"

[learning]
enabled = false
update_interval = 100
# auto_update = false

[learning.routing]
policy = "heuristic"
# min_samples = 5

# [learning.intelligence]
# policy = "none"              # "sft" to learn from traces

# [learning.agent]
# policy = "none"              # "agent_advisor" | "icl_updater"

# [learning.metrics]
# accuracy_weight = 0.6
# latency_weight = 0.2
# cost_weight = 0.1
# efficiency_weight = 0.1

# [learning.proving]
# enabled = false              # Model Proving Ground: A/B new models on your traces
# auto_trigger = false         # prove automatically when a new model appears
# auto_adopt = false           # adopt winners without `nova prove adopt`
# min_margin = 0.05            # per-class accuracy margin required to adopt
# min_samples = 10             # min benchmark samples synthesized from traces
# max_samples = 60             # cap on benchmark size
# schedule = ""                # cron for the watcher/prove task
# incumbent = ""               # default opponent; "" uses intelligence.default_model
# judge_engine = "local"       # "local" | "cloud"
# judge_model = ""             # "" judges with the incumbent model (same judge both sides)

# [learning.consolidation]
# enabled = false              # Memory sleep cycle: distill traces into core facts
# schedule = ""                # cron expression; empty = run manually
# min_session_messages = 6     # skip clusters smaller than this
# max_facts_per_run = 50       # cap on facts distilled per run
# judge_model = ""             # "" uses intelligence.default_model
# decay_days = 90              # facts untouched this long stop being served
# core_memory_max_chars = 4000 # core-memory block budget

# [learning.skillforge]
# enabled = false              # Skill Foundry: synthesize skills from repeated tool runs
# auto_trigger = false         # forge automatically when patterns accrue
# auto_adopt = false           # install passing skills without `nova forge adopt`
# min_pattern_count = 3        # same tool-sequence must appear this often
# min_feedback = 0.7           # average trace feedback required to mine a pattern
# max_candidates_per_run = 3   # cap on skills synthesized per run
# sandbox_timeout = 30.0       # seconds per sandboxed replay step
# judge_model = ""             # "" uses intelligence.default_model

# [learning.training]
# enabled = false              # self-training: mine traces, LoRA, deploy
# min_pairs = 50               # SFT pairs needed before a run is worth starting
# auto_apply = false           # deploy without `nova train deploy` (gate still applies)
# dpo_enabled = false          # DPO preference lane (train from fork/race winners)
# dpo_min_pairs = 20           # preference pairs needed before a DPO run starts
# dpo_tag_prefix = "nova-dpo"  # Ollama tag for DPO adapters

# [learning.fleet]
# share_reports = false        # Fleet Oracle: opt-in sharing of anonymized reports
# dataset_repo = ""            # git URL of the shared fleet dataset repo
# min_calls_per_model = 5      # k-anonymity: drop models with fewer calls
# since_days = 30              # aggregation window for report building
# cache_dir = ""               # "" uses ~/.nova_ai/fleet/cache for the dataset clone

[telemetry]
enabled = true
# gpu_metrics = false
# gpu_poll_interval_ms = 50

[traces]
enabled = false

[channel]
enabled = false
default_agent = "simple"

# [channel.telegram]
# bot_token = ""  # Or set TELEGRAM_BOT_TOKEN env var

# [channel.discord]
# bot_token = ""  # Or set DISCORD_BOT_TOKEN env var

# [channel.slack]
# bot_token = ""  # Or set SLACK_BOT_TOKEN env var

# [channel.webhook]
# url = ""

# [channel.whatsapp]
# access_token = ""      # Or set WHATSAPP_ACCESS_TOKEN env var
# phone_number_id = ""   # Or set WHATSAPP_PHONE_NUMBER_ID env var

# [channel.signal]
# api_url = ""            # signal-cli REST API URL
# phone_number = ""       # Or set SIGNAL_PHONE_NUMBER env var

# [channel.google_chat]
# webhook_url = ""        # Or set GOOGLE_CHAT_WEBHOOK_URL env var

# [channel.irc]
# server = ""
# port = 6667
# nick = ""
# use_tls = false

# [channel.teams]
# app_id = ""             # Or set TEAMS_APP_ID env var
# app_password = ""       # Or set TEAMS_APP_PASSWORD env var

# [channel.matrix]
# homeserver = ""         # Or set MATRIX_HOMESERVER env var
# access_token = ""       # Or set MATRIX_ACCESS_TOKEN env var

# [channel.mattermost]
# url = ""                # Or set MATTERMOST_URL env var
# token = ""              # Or set MATTERMOST_TOKEN env var

# [channel.feishu]
# app_id = ""             # Or set FEISHU_APP_ID env var
# app_secret = ""         # Or set FEISHU_APP_SECRET env var

# [channel.bluebubbles]
# url = ""                # Or set BLUEBUBBLES_URL env var
# password = ""           # Or set BLUEBUBBLES_PASSWORD env var

[security]
enabled = true
mode = "warn"
scan_input = true
scan_output = true
secret_scanner = true
pii_scanner = true
enforce_tool_confirmation = true
ssrf_protection = true
# rate_limit_enabled = false
# rate_limit_rpm = 60
# rate_limit_burst = 10

# [sandbox]
# enabled = false
# image = "nova_ai-sandbox:latest"
# timeout = 300
# max_concurrent = 5
# runtime = "docker"

# [scheduler]
# enabled = false
# poll_interval = 60
# db_path = ""                # Defaults to ~/.nova_ai/scheduler.db

# [channel.whatsapp_baileys]
# auth_dir = ""               # Defaults to ~/.nova_ai/whatsapp_auth
# assistant_name = "Nova"
# assistant_has_own_number = false
"""
    if host:
        import re as _re

        pattern = _re.escape(f"[engine.{engine}]") + r"\nhost = \"[^\"]*\""
        replacement = f'[engine.{engine}]\\nhost = "{host}"'
        result = _re.sub(pattern, replacement, result)
    return result
